### ISSUE TITLE
Alt and cmd keys swap

### ISSUE THREAD

**Issue by millcek** [jesperhh/WinK760#2]
Hello, thanks for the app! I would like to add functionality for swapping alt with cmd to make it more win-like. I just checked the code and though where I could add it but as I am not so familiar with C++ I would spend too much time for that. Could you please give me a hint? Thanks.

**Comment by jesperhh** [comment]
I'm glad you like it!
Regarding remapping the alt/cmd key, I decided not to implement this inside this application, as Windows can remap the keys at a lower level with the right registry editing. I used SharpKeys to edit the registry to remap alt and cmd, but if you want to, you could make WinK760 do the remap on first startup.

**Comment by millcek** [comment]
Yes, it is possible but I would like to change it for the K760 only because I also use the laptop keyboard. Is it possible or the only way is to remap the keys for a whole system?

**Comment by jesperhh** [comment]
It is possible, but not trivial, you could look at https://github.com/oblitum/Interception which talks to the window kernel to remap keys.
