### ISSUE TITLE
Crash on windows 10

### ISSUE THREAD

**Issue by khariche** [jesperhh/WinK760#4]
Hi,

Thank you for this wonderful little gem. It worked for a while - a few months -, but I am not able to make it work anymore. Whenever I launch it, it sits in the tray area, but does nothing, and when I try to clik the tray icon, it closes automatically, without any further explanation.
It is only when the keyboard is disconnected that I am able to click on the tray icon and see the pop up window with the keyboard image, without the tray icon disappearing suddenly.
I was able to retrieve a crash message from windows (see at the end of my message), I hope it can help solve the issue. I have tried reading it, but none of it makes any sense to me.
I use several autohotkey scripts for other things, as well as well as X-Mouse Button Control, in case it makes any difference...

OS version: windows 10 home 1903 - build 18362.449
Thank you so much in advance.

Cheers.

Crash message from windows ("report.wer" file):

Version=1
EventType=APPCRASH
EventTime=132173708546666123
ReportType=2
Consent=1
UploadTime=132173708552261147
ReportStatus=268435456
ReportIdentifier=6d4b6277-eb36-4caf-af9a-759b2d75f65a
IntegratorReportIdentifier=8b88e7a7-239f-4a2a-9702-1cda2b58e81d
Wow64Host=34404
Wow64Guest=332
NsAppName=WinK760.exe
AppSessionGuid=00011d68-0002-0023-118b-8d9d4993d501
TargetAppId=W:00065859131e2c3ff92770e79decca0a06c30000ffff!0000cd1c9e2b88eac8c2116573a826af8b11ec8bc2f4!WinK760.exe
TargetAppVer=2017//11//06:20:07:53!833ef!WinK760.exe
BootId=4294967295
ServiceSplit=1958150144
TargetAsId=15990
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=653e005c8134f9a564d13e52b6bdd98b
Response.BucketTable=1
Response.LegacyBucketId=1500048675865221515
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=WinK760.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=5a00c119
Sig[3].Name=Fault Module Name
Sig[3].Value=WinK760.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5a00c119
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=00004920
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.18362.2.0.0.768.101
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=2beb
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=2beba6fb4680d73a8c78ca7c24ccdb46
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=e912
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=e912ddbe3f2150e5cb48514d40be2fb5
UI[2]=X:\m\Syncthing\WinK760.exe
LoadedModule[0]=X:\m\Syncthing\WinK760.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\SYSTEM32\apphelp.dll
LoadedModule[5]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[6]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[7]=C:\WINDOWS\System32\sechost.dll
LoadedModule[8]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[9]=C:\WINDOWS\System32\SspiCli.dll
LoadedModule[10]=C:\WINDOWS\System32\CRYPTBASE.dll
LoadedModule[11]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[12]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[13]=C:\WINDOWS\System32\win32u.dll
LoadedModule[14]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[15]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[16]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[17]=C:\WINDOWS\System32\USER32.dll
LoadedModule[18]=C:\WINDOWS\System32\SETUPAPI.dll
LoadedModule[19]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[20]=C:\WINDOWS\System32\bcrypt.dll
LoadedModule[21]=C:\WINDOWS\System32\SHELL32.DLL
LoadedModule[22]=C:\WINDOWS\System32\shcore.dll
LoadedModule[23]=C:\WINDOWS\System32\combase.dll
LoadedModule[24]=C:\WINDOWS\System32\windows.storage.dll
LoadedModule[25]=C:\WINDOWS\System32\profapi.dll
LoadedModule[26]=C:\WINDOWS\System32\powrprof.dll
LoadedModule[27]=C:\WINDOWS\System32\UMPDC.dll
LoadedModule[28]=C:\WINDOWS\System32\shlwapi.dll
LoadedModule[29]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[30]=C:\WINDOWS\System32\cryptsp.dll
LoadedModule[31]=C:\WINDOWS\SYSTEM32\bthprops.cpl
LoadedModule[32]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[33]=C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.449_none_71d3f4435ae6e118\COMCTL32.DLL
LoadedModule[34]=C:\WINDOWS\SYSTEM32\DEVOBJ.dll
LoadedModule[35]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[36]=C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.18362.449_none_2e74e93c278899ad\comctl32.dll
LoadedModule[37]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[38]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[39]=C:\WINDOWS\system32\IconCodecService.dll
LoadedModule[40]=C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
LoadedModule[41]=C:\WINDOWS\SYSTEM32\hid.dll
LoadedModule[42]=C:\WINDOWS\System32\WINTRUST.dll
LoadedModule[43]=C:\WINDOWS\System32\MSASN1.dll
LoadedModule[44]=C:\WINDOWS\System32\CRYPT32.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=18362
OsInfo[3].Key=ubr
OsInfo[3].Value=449
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=84
OsInfo[8].Key=sku
OsInfo[8].Value=101
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=768
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=215881
OsInfo[15].Key=osinsty
OsInfo[15].Value=1
OsInfo[16].Key=iever
OsInfo[16].Value=11.418.18362.0-11.0.155
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=8072
OsInfo[19].Key=svolsz
OsInfo[19].Value=237
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=190318
OsInfo[22].Key=bldtm
OsInfo[22].Value=1202
OsInfo[23].Key=bldbrch
OsInfo[23].Value=19h1_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.18362.449.amd64fre.19h1_release.190318-1202
OsInfo[30].Key=buildflightid
OsInfo[30].Value=2ABBFE8A-57A7-4ECE-870E-2008A39B7D9D.1
OsInfo[31].Key=edition
OsInfo[31].Value=Core
OsInfo[32].Key=ring
OsInfo[33].Key=expid
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=WinK760.exe
AppPath=X:\m\Syncthing\WinK760.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=C97DB79A60D655F2CEA2592A5E371E21
MetadataHash=-1205107016

**Comment by jesperhh** [comment]
Unfortunately, I cannot gather anything useful from that crash information. While I dig out the keyboard (I don't use it myself anymore, but I still have it somewhere), could you verify if it crashes when running by itself (close as many programs not part of Windows as possible)?

**Comment by khariche** [comment]
Hi,

First of all, thank you so much for your answer. I already tried running it
on a freshly started windows session, before running anything else.
If there is any other way i can gather troubleshooting info, please let me
know.
Cheers

**Comment by khariche** [comment]
Hi, by any chance, would it be possible to achieve the same result with
autohotkey? Any clues as to how I could do that? I am no programmer
myself...
Thank you very much!

**Comment by jesperhh** [comment]
Unfortunately not, if you press F1 without F-Lock, nothing is ever sent to the computer, so it is not possible to simply re-map the keys. What this program does is send a special packet to the keyboard to tell it to switch the F-lock mode.

Could you try one of the new builds (either the 32 bit or the 64 bit one)? I could no reproduce the issue here, but I have updated the build system to be Windows based, and used the newest compilers.

**Comment by khariche** [comment]
Thank you so much for looking into this ! I downloaded the 64 bit build...
When downloading, my browser (brave, based on chromium) warned me that the
file was potentially dangerous. After that, whe opening the file, i got a
warning from windows itself, saying that I shouldn't run the executable.
[image: image.png]
Discarded the warning but unfortunately, same problem, the program closes
just right after being executed. Then I figured I would try the 32 build,
same warning, and then, when I tried opening it, I got the following error
message:

[image: image.png]

So this seems to confirm the reason why your program closes so quickly is
because it is being terminated by the windows security system. I don't have
any additional antivirus installed, just windows defender...

**Comment by khariche** [comment]
After disabling some options in windows defender I get this warning,
[image: image.png]
I confirm to run the program, but the result is the same...

Thanks again.

**Comment by khariche** [comment]
Running it as administrator doesn't change anything.

**Comment by jesperhh** [comment]
The reason for the antivirus warnings is that it is very 'fresh' software, which the antivirus doesn't know about - they assume (wrongly) that that is bad thing..

Could you try to create a full crash dump and upload it somewhere following the steps in the top answer in this post:
https://stackoverflow.com/questions/30121822/how-to-generate-windows-memory-dump-when-application-crashes
That might help narrow it down, as I cannot reproduce the issue here.

**Comment by jesperhh** [comment]
..You can also try the latest version - I have tried to go over the code once more and eliminate any possible issues, as well as update to the latest version of the hidapi dependency.

**Comment by khariche** [comment]
Oh my God! it works!!! Thank you soooooooooooo much!!! Really!!!
Do you think it would be possible at all to get the "f13" mapped to the delete key, or at least recognized, so that I can remap it with autohotkey?
What about swapping the RWin and RAlt keys?
Of course, these are only suggestions to make your program even better, but again, thank you so much for taking the time to fix the basic functionality!

**Comment by jesperhh** [comment]
That is great news! 

The remapping is much easier to do with other applications, I don't think there is any reason to build it in to WinK760. I personally use [SharpKeys](https://github.com/randyrants/sharpkeys) to remap caps-lock to escape but you can use it to remap almost any key.

**Comment by khariche** [comment]
OK, thank you.
The problem with sharpkeys or any other key remapper that I know of is that
they are not hardware dependent. Ideally, I would like a solution that
remaps only for the k760, and not for the other keyboards I use.
What about the "f13" - eject key, which I cannot get the code for in
autohotkey (doesn't even register as a key press)?
Again, thanks for all your help.

**Comment by jesperhh** [comment]
SharpKeys should detect the Eject key as F13 and allow you to remap it when WinK760 is running (WinK760 listens to a different channel where this key press is sent and transforms it into 'F13').

Doing the remapping per keyboard is possible, but it requires custom kernel drivers, which I feel is a bit outside the scope of this application.

**Comment by khariche** [comment]
Ok, thank you so much for your help and answers.
Best regards

**Comment by jesperhh** [comment]
You are welcome!
